spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaeeks?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMillis=500
    validationQuery: select 'x'
    initialization-mode: never
logging:
  file:
    name: log/springboot-javaeeks.log
  level:
    com.springboot.springbootjavaeeks: debug